language: rust
matrix:
  include:
    # linux
    - rust: stable
      os: linux
    - rust: beta
      os: linux
    - rust: nightly
      os: linux
      env: STRICT=true
    # osx
    - rust: stable
      os: osx
    - rust: beta
      os: osx
    - rust: nightly
      os: osx

# Request the "secret" GCE VM environment (faster + more memory)
sudo: 9000

script:
  - if [ "$STRICT" = true ]; then
      travis_wait cargo build --verbose --no-default-features --features strict;
    else
      travis_wait cargo build --verbose --no-default-features;
    fi
  - if [ "$STRICT" = true ]; then
      travis_wait cargo build --verbose --no-default-features --features 'strict ws';
    else
      travis_wait cargo build --verbose --no-default-features --features ws;
    fi
  - if [ "$STRICT" = true ]; then
      travis_wait cargo build --verbose --no-default-features --features 'strict proto';
    else
      travis_wait cargo build --verbose --no-default-features --features proto;
    fi
  - if [ "$STRICT" = true ]; then
      travis_wait cargo build --verbose --features strict;
    else
      travis_wait cargo build --verbose;
    fi
  - if [ "$STRICT" = true ]; then
      travis_wait cargo test --verbose --features strict;
    else
      travis_wait cargo test --verbose;
    fi
  - travis_wait cargo doc --verbose --no-deps
  - if [ "$STRICT" = true ]; then
      travis_wait cargo install --git 'https://github.com/rust-lang-nursery/rustfmt' --verbose &&
      cargo fmt -- --write-mode diff;
    fi
  - if [ "$STRICT" = true ]; then
      grep -rL 'This Source Code Form is subject to the terms of the Mozilla Public License' src
      && grep -rL 'This Source Code Form is subject to the terms of the Mozilla Public License' tests
      ;
    fi
